[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "asmesh"
description = "3D processing library"
authors = [
    { name = "alpinebuster", email = "imzqqq@hotmail.com" },
]
readme = "README.md"
license = { file = "LICENSE" }
classifiers = [
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "License :: Free For Educational Use",
    "License :: Free for non-commercial use",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
]
requires-python = ">=3.8"
dependencies = [
    "numpy >= 1.19.0",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://meshsdk.tech/"
Documentation = "https://meshsdk.tech/documentation/"
Source = "https://github.com/alpinebuster/meshsdk"
"Bug Reports" = "https://github.com/alpinebuster/meshsdk/issues"
